#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: John Doe
author: "John Doe"

# Short bio or description (displayed in the header)
description: "Web Developer passionate about photography"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "assets/images/avatar.jpg"

timezone: Europe/Rome

#
# Flags below are optional
#

# Theme Engine
# To change site-wide fonts and colors, go to _sass/_variables anche change the hex values.

# Writing anything to enable search, leave it blank to disable
embedsearch: true

# Includes a social icon in social divs for each username you enter
social-links:
  dribbble:
  email: inbox@fpira.com
  facebook: john-doe
  flickr: john-doe
  github: pirafrank
  instagram:
  linkedin: fpira
  pinterest: john-doe
  rss: stuff # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: pirafrank
  stackoverflow: users/12345/john-doe # your stackoverflow profile, e.g. "users/12345/john-doe"
  youtube: john-doe # channel/<your_long_string> or user/<user-name>
  googleplus: +johndoe # e.g. https://plus.google.com/+johndoe

# Type your email with **1 space** between each character.
# Don't worry, it will be displayed correctly.
# For example: inbox@fpira.com -> inbox@nospampleasefpira.com
# NOTE: Don't leave it empty or the link in About page won't work.
encryptedemail: "i n b o x @ f p i r a . c o m"

# Home customisation
home:
  show_pinboard: true # set it to true to enable, false to disable right section in home
  max_posts: 3 # max number of latest posts to show in home page
  show_social: false # choose whether to display social link in mid of home page or not
  show_search: true # choose whether to display search in home or not

# Choose whether to display social links in footer or not
footersocial: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-1234567-1) to activate tracking
google_analytics: ""

# Your website URL (e.g. http://fpira.com)
# Used for Sitemap.xml and your RSS feed
url: http://fpira.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: '/:year/:month/:title/'
excerpt_separator: "\n\n"

# Jekyll Blue version in use
version: v0.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # If you want to un-minify, set to :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
